# Generated by Django 2.2 on 2019-04-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('id_prerequisite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id_group', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=512)),
                ('answer_1', models.CharField(max_length=40)),
                ('answer_2', models.CharField(max_length=40)),
                ('answer_3', models.CharField(max_length=40)),
                ('answer_4', models.CharField(max_length=40)),
                ('answer_right', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('points', models.IntegerField()),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
